export const ORDER_ROLLBACK_CREATE_REQUEST = 'ORDER_ROLLBACK_CREATE_REQUEST';
export const ORDER_ROLLBACK_CREATE_SUCCESS = 'ORDER_ROLLBACK_CREATE_SUCCESS';
export const ORDER_ROLLBACK_CREATE_FAIL = 'ORDER_ROLLBACK_CREATE_FAIL';
export const ORDER_ROLLBACK_CREATE_RESET = 'ORDER_ROLLBACK_CREATE_RESET';

export const ORDER_ROLLBACK_LIST_REQUEST = 'ORDER_ROLLBACK_LIST_REQUEST';
export const ORDER_ROLLBACK_LIST_SUCCESS = 'ORDER_ROLLBACK_LIST_SUCCESS';
export const ORDER_ROLLBACK_LIST_FAIL = 'ORDER_ROLLBACK_LIST_FAIL';
export const ORDER_ROLLBACK_LIST_RESET = 'ORDER_ROLLBACK_LIST_RESET';

export const ORDER_ROLLBACK_HANDLE_REQUEST = 'ORDER_ROLLBACK_HANDLE_REQUEST';
export const ORDER_ROLLBACK_HANDLE_SUCCESS = 'ORDER_ROLLBACK_HANDLE_SUCCESS';
export const ORDER_ROLLBACK_HANDLE_FAIL = 'ORDER_ROLLBACK_HANDLE_FAIL';
export const ORDER_ROLLBACK_HANDLE_RESET = 'ORDER_ROLLBACK_HANDLE_RESET';

export const ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_REQUEST = 'ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_REQUEST';
export const ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_SUCCESS = 'ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_SUCCESS';
export const ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_FAIL = 'ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_FAIL';
export const ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_RESET = 'ORDER_ROLLBACK_UPDATE_ADMIN_WATCH_RESET';
